export enum FamilyTreeErrorCode {
  PERSON_NOT_FOUND = "PERSON_NOT_FOUND",
  DUPLICATE_PERSON = "DUPLICATE_PERSON",
  INVALID_SPOUSE = "INVALID_SPOUSE",
  ALREADY_MARRIED = "ALREADY_MARRIED",
  CHILD_ADDITION_FAILED = "CHILD_ADDITION_FAILED",
  INVALID_RELATIONSHIP = "INVALID_RELATIONSHIP",
}
